-- 영화 오펜하이머에 출연한 감독과 배우들을 조회하는 쿼리
SELECT MO_TITLE AS 영화제목, RO_ROLE AS 역할, FP_NAME AS 이름 
FROM MOVIE
JOIN ROLE 
ON MO_NUM = RO_MO_NUM
JOIN FILM_PERSON
ON FP_NUM = RO_FP_NUM;

-- 영화 기본정보를 조회하는 쿼리
SELECT * FROM MOVIE WHERE MO_TITLE='오펜하이머';

-- 영화 오펜하이머의 트레일러와 스틸컷 파일의 개수 조회하는 쿼리
SELECT COUNT(*) AS 파일개수 FROM MOVIE_FILE WHERE MF_MO_NUM IN (SELECT MO_NUM FROM MOVIE WHERE MO_TITLE = '오펜하이머');


-- ABC123 회원이 예매한 내역 조회 (영화명, 시간, 좌석명,
SELECT MO_TITLE AS 영화명, SD_DATE AS 날짜, SD_START_TIME AS 시작시간, SD_END_TIME AS 종료시간, SE_NAME AS 좌석번호  
FROM RESERVATION 
JOIN RESERVATION_LIST ON RV_NUM = RL_RV_NUM
JOIN SEAT ON RL_SE_NUM = SE_NUM
JOIN SCHEDULE ON RV_SD_NUM = SD_NUM
JOIN MOVIE ON SD_MO_NUM = MO_NUM
WHERE RV_ME_ID = 'abc123';

-- 티켓별로 좌석 번호가 아닌 성인, 청소년 수 조회 
SELECT SUM(RV_ADULT) AS 성인수, SUM(RV_CHILD) AS 청소년수
FROM RESERVATION 
JOIN SCHEDULE ON RV_SD_NUM = SD_NUM
JOIN MOVIE ON SD_MO_NUM = MO_NUM
WHERE RV_ME_ID = 'abc123'
GROUP BY RV_NUM;


-- 강남점에서 콘크리트 유토피아 20ㅣ50에 예매 가능한 좌석을 조회하는 쿼리
SELECT  *  
FROM SEAT
JOIN SCREEN ON SE_SC_NUM = SC_NUM
JOIN SCHEDULE ON SD_SC_NUM = SC_NUM
WHERE SD_NUM = 8 AND SE_NAME NOT IN
(SELECT * FROM RESERVATION 
JOIN RESERVATION_LIST ON RL_RV_NUM = RV_NUM
WHERE RV_SD_NUM=8);

SELECT  *  
FROM SEAT
JOIN SCREEN ON SE_SC_NUM = SC_NUM
JOIN SCHEDULE ON SD_SC_NUM = SC_NUM
LEFT JOIN RESERVATION ON RV_SD_NUM = SD_NUM
LEFT JOIN RESERVATION_LIST ON RL_RV_NUM = RV_NUM;


SELECT SE_NAME 
FROM SEAT
WHERE SE_NAME NOT IN(SELECT SE_NAME FROM SCHEDULE
JOIN RESERVATION ON SD_NUM = RV_SD_NUM
JOIN RESERVATION_LIST ON RV_NUM = RL_RV_NUM
JOIN SEAT ON RL_SE_NUM = SE_NUM
WHERE SD_START_TIME = '20:50:00');







